config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'

  resources :contacts, only: [:new, :create] do
    collection do
      get 'about'
    end
  end
  resources :posts, only: [:index, :show]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      add_admin_rules
    elsif user && user.persisted?
      add_user_rules(user)
    end
    can :create, User
  end

  private

  def add_admin_rules
    can :access, :rails_admin
    can :manage, :all
    cannot [:destroy], User
    can :dashboard
  end

  def add_user_rules(user)
  #  can :read, Challenge
  #  can :create, CompletedChallenge
  #  can [:read, :update], CompletedChallenge, user_id: user.id
    can [:read, :update], User, id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor(:email, :subject, :body)

  validates :email, :subject, :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  scope :ordered_by_id, -> { order(id: :asc)  }
  scope :only_published, -> { where(published: true) }

  validates_presence_of :title, :description, :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_current_location, unless: :devise_controller?
  protect_from_forgery with: :exception

  def store_current_location
    store_location_for(:user, request.url)
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = exception.message
    redirect_to main_app.root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :city, :phone,
                                                       :role])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      FormMailer.contact_msg(@contact.email, @contact.subject, @contact.body).deliver_now
      redirect_to root_path
    else
      render :new
    end
  end

  def about
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :subject, :body)
  end
end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.only_published
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.only_published.ordered_by_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  FORMAT = AutoHtml::Pipeline.new(
    AutoHtml::Youtube.new(750, 400),
    AutoHtml::Vimeo.new(750, 400),
    AutoHtml::GithubMarkDown.new
  )

  def html_for(content)
    #safe_join [raw(FORMAT.call(content))]
    FORMAT.call(content).html_safe
  end
end

app/views/contacts/about.html.erb
<div class="container">
  <div class="col-xs-12 col-md-12 col-lg-12">
    <div class="row">
      <div class="post-overview">
        <article>
          <h2 class="text-center">Sobre mim:</h2>
          <br>
          <div class="col-xs-12 col-md-12 col-lg-12">
            <div class="row">
              <p class="text-center">"Tudo o que tem que ser feito, merece ser bem feito."</p>
              <br>
              <%= image_tag 'ideia.png', alt: 'Ideia', class: "img-thumbnail idea-photo" %><br><br><br>
              <br>
            </div>
          </div>
          <h3 class="text-center">Formação Acadêmica</h3><br>
          <div class="row">
            <div class="col-xs-12 col-md-6 col-lg-6">
              <p class="text-center">Colegio Oswaldo Cruz</p>
              <p class="text-center">Curso Técnico em Informática</p>
              <p class="text-center">Ano de formação: 2009</p>
              <%= image_tag 'brasao_oc.png', alt: 'OC', class: "img-thumbnail about-photo" %><br><br>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-6">
              <p class="text-center">Universidade Paulista</p>
              <p class="text-center">Bacharel em Sistemas de Informacao</p>
              <p class="text-center">Ano de formação: 2016</p>
              <%= image_tag 'brasao_unip.png', alt: 'UNIP', class: "img-thumbnail about-photo" %><br><br>
            </div>
          </div>
          <br>
          <h3 class="text-center">Experiência Profissional</h3><br>
          <div class="row">
            <div class="col-xs-12 col-md-6 col-lg-6">
              <p class="text-center">Exército Brasileiro</p>
              <p class="text-center">3º sargento técnico em informática</p>
              <p class="text-center">Período: fev 2011 - fev 2016 </p>
              <%= image_tag 'brasao_eb.png', alt: 'EB', class: "img-thumbnail about-photo" %><br><br>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-6">
              <p class="text-center">Campus Code</p>
              <p class="text-center">Desenvolvedor Web - Ruby on Rails</p>
              <p class="text-center">Período: abr 2017 - até agora</p>
              <%= image_tag 'campus_code.png', alt: 'CD', class: "img-thumbnail about-photo" %><br><br>
            </div>
          </div>
          <br>
          <h3 class="text-center">Hobbies</h3><br>
          <div class="row">
            <div class="col-xs-12 col-md-4 col-lg-4">
              <p class="text-center">Running</p>
              <%= image_tag 'running.jpg', alt: 'Run', class: "hobby-photo" %><br><br>
            </div>
            <div class="col-xs-12 col-md-4 col-lg-4">
              <p class="text-center">Patins</p>
              <%= image_tag 'patins.jpg', alt: 'Roller', class: "hobby-photo" %><br><br>
            </div>
            <div class="col-xs-12 col-md-4 col-lg-4">
              <p class="text-center">Airsoft</p>
              <%= image_tag 'airsoft.png', alt: 'Air', class: "hobby-photo" %><br><br>
            </div>
          </div>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<%= notice %>
<div class="container">
    <div class="col-xs-12 col-md-12 col-lg-12">
      <div class="row">
        <div class="panel panel-default">
        <h2 class="panel-heading">Entre em contato!</h2>
        <div class="panel-body">
          <%= simple_form_for(@contact, html: { class: 'form-horizontal' }) do |f| %>
            <div class="col-xs-10 col-xs-offset-1 col-lg-10 col-lg-offset-1">
              <div class="row">
                <%= f.input :email, label: 'Seu email:',
                  placeholder: 'meuemail@dominio.com', class: "form-control" %>
              </div>
            </div>
            <div class="col-xs-10 col-xs-offset-1 col-lg-10 col-lg-offset-1">
              <div class="row">
                <%= f.input :subject, label: 'Assunto:'%>
              </div>
            </div>
            <div class="col-xs-10 col-xs-offset-1 col-lg-10 col-lg-offset-1">
              <div class="row">
                <%= f.input :body, label: 'Mensagem:'%>
              </div>
            </div>
            <div class="form-actions">
              <div class="col-xs-10 col-xs-offset-1 col-lg-10 col-lg-offset-1">
                <div class="row">
                  <%= f.button :submit, 'Enviar', class: "btn btn-primary btn-md" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/curriculums/index.html.erb
<h1>Meus dados</h1>

app/views/home/index.html.erb
<%= render 'shared/carousel' %>
<div class="container">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portifolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon_hrq_circle.ico'), rel: 'icon', type: "image/x-icon" %>
  </head>

  <body>
    <header>
      <div class="container">
        <%= render 'shared/menu' %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer class="text-center">
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
  <div class="col-xs-12 col-md-12 col-lg-12">
    <div class="row">
      <div class="panel panel-default">
        <% @posts.each do |post| %>
          <div class="panel-heading">
            <h2><%= link_to post.title, post_path(post), class: "btn-post" %></h2>
          </div>
          <div class="panel-body">
            <div class="text-center">
              <%= post.description %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-lg-8">
      <div class="post-overview">
        <article>
          <h1><%= @post.title %></h1>
          <%= html_for(@post.body) %>
          <br>
          <p><b>Criado em - <%= l @post.created_at, format: :long  %></b></p>
          <br><br>
          <%= render 'shared/disqus' %>
        </article>
      </div>
    </div>
    <div class="col-xs-12 col-md-4 col-lg-4">
      <h3>Outros Posts:</h3>
      <% @posts.each do |other_post| %>
        <% next if other_post.id == @post.id %>
        <%= link_to other_post.title, post_path(other_post) %>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div id="carousel-banner" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-banner" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-banner" data-slide-to="1"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active" style="background-image: url(<%= image_url 'cup.jpg' %>)">
      <div class="carousel-caption caption-center">
        <h2>Últimos posts!!</h2>
        <p>
        <%= link_to 'Quero ler', posts_path, class: 'btn btn-lg ' %>
        </p>
      </div>
    </div>
    <div class="item" style="background-image: url(<%= image_url 'code.jpg' %>)">
      <div class="carousel-caption caption-center">
        <h2>Currículo Simplificado</h2>
        <p>
        <%= link_to "click_on 'here'", about_contacts_path, class: 'btn btn-lg ' %>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-banner" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-banner" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

var disqus_config = function () {
  this.shortname = 'portifolio-coments';
  this.page.url = '<%= url_for(host: 'henriquepanham.herokuapp.com') %>';
  this.page.identifier = '<%= @post.id %>';
  this.page.title = '<%= @post.title %>';
};

(function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = 'https://portifolio-coments.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/shared/_footer.html.erb
<div class="social-media">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-12 col-lg-12">
        <h3>Henrique Panham</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-6 col-md-2 col-lg-2 col-xs-offset-3 col-md-offset-5 col-lg-offset-5">
        <%= image_tag 'eu.jpg', alt: 'Eu', class: "perfil-photo" %><br><br>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <h4>Ruby on Rails Developer</h4>
      </div>
    </div>
  </div>
  <div class="footer-below">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <a href="http://fb.com/henrique.panham" target="_blank" alt="Link para o meu perfil do Facebook"><i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i></a>
          <a href="https://github.com/henriquepjv" target="_blank" alt="Link para o meu GitHub"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a>
          <a href="https://www.linkedin.com/in/henrique-panham-junqueira-1454b2b3" target="_blank" alt="Link para o meu LinkedIn"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="navbar-home">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" 
                            data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Ver Menu</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h1>
      <a class="navbar-brand" href="<%= root_path %>" title="HRQPJV"></a>
      </h1>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul id="main-nav" class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete do %>
              <i class="fa fa-power-off" aria-hidden="true"></i><span class="icon-text">Sair</span>
            <% end %>
          </li>
        <% end %>

        <li>
          <%= link_to posts_path do %>
            <i class="fa fa-graduation-cap" aria-hidden="true"></i><span class="icon-text">Blog</span>
          <% end %>
        </li>
        <li>
          <%= link_to about_contacts_path do %>
            <i class="fa fa-address-card-o" aria-hidden="true"></i><span class="icon-text">Sobre</span>
          <% end %>
        </li>
        <li>
          <%= link_to new_contact_path do %>
            <i class="fa fa-bullhorn" aria-hidden="true"></i><span class="icon-text">Contato</span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>